---
title: "Data Manipulation"
author: "Briana Lettsome"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Import FAS csv files

Import my first csv.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
```

##Look at data

Look at data.

```{r}
head(litters_data)

skimr::skim(litters_data)
```
### Pup dataset

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)
```

```
litters_data = read_csv("./Data Import Example/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./Data Import Example/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```



```
select(litters_data, litter_number, starts_with ("pups"))
`````

pups_data = read_csv("./Data Import Example/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

## Filter observations

Do some filtering!!

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)

library(tidyverse)